site_name: UQ PHYS3080 Distance Ladder Project
nav:
    - Home: index.md
    - Learning Python: software.md
    - 'Analysing Data in Python':
        - HR Diagrams: notebooks/hr_diagram.ipynb
        - Periodograms: notebooks/lombscargle_example.ipynb
    - Matlab Scripts: matlab.md

theme:
  name: "material"
repo_url: https://github.com/benjaminpope/ladder
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates